import { Inter } from "next/font/google";
import "./globals.css";
// import { GoogleAnalytics } from "@next/third-parties/google";
import GoogleAnalytics from "./components/GoogleAnalytics";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "The Game Vault",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GoogleAnalytics />
      <body className={inter.className}>{children}</body>
      {/* <GoogleAnalytics gaId="G-CV2LC5MQKB" /> */}
    </html>
  );
}
